[Lou Zhanzhi] iP
nus-cs2103-AY2425S1/ip pull request #308
Opened 2024-08-27 09:20 UTC by zzzlou

2024-09-05 06:52 UTC, antgyf requested changes
LGTM other than a few nits
- consider case if time is omitted from deadline or event, or case where deadline and time format is wrong.

2024-09-06 12:53 UTC, yooplo reviewed
Overall, very well done! I could not find much to nitpick on stylewise. A few small updates suggested.

2024-09-06 12:53 UTC, yooplo commented on src/main/java/zzbot/DialogBox.java
> +
I would think that javadocs should be added here since it is a public method.

2024-09-06 12:53 UTC, yooplo commented on src/main/java/zzbot/Storage.java
> +
extra line here haha

2024-09-06 12:53 UTC, yooplo commented on src/main/java/zzbot/Ui.java
> +
another extra line here oops

2025-09-01 04:36 UTC, closed without merging